/*
 * DialogoConfirmacao.java
 *
 * Created on 5 de Dezembro de 2002, 20:17
 */

package dialogos;

/**
 *
 * @author  regisb
 */
public class DialogoConfirmacao extends javax.swing.JDialog {
    
    /** Creates new form DialogoConfirmacao */
    public DialogoConfirmacao(java.awt.Frame parent, boolean modal, String titulo, String texto) {
        super(parent, modal);
        initComponents();
        setTitle(titulo);
        lblMensagem.setText(texto);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        painel = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();

        setTitle("");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        painel.setLayout(null);

        painel.setPreferredSize(new java.awt.Dimension(295, 112));
        painel.setName("painel");
        lblMensagem.setText("texto");
        lblMensagem.setForeground(new java.awt.Color(0, 0, 153));
        lblMensagem.setName("lblMensagem");
        painel.add(lblMensagem);
        lblMensagem.setBounds(10, 10, 250, 40);

        btnOk.setMnemonic('O');
        btnOk.setText("Ok");
        btnOk.setName("btnOk");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        painel.add(btnOk);
        btnOk.setBounds(90, 70, 95, 33);

        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new DialogoConfirmacao(new javax.swing.JFrame(), true, "", "").show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
    
}
