/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static sun.security.jgss.GSSUtil.login;


/**
 *
 * @author Rafael
 */
public class longin extends javax.swing.JFrame {
       ConexaoBD con= new ConexaoBD();
    DateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
   
    /**
     * Creates new form longin
     */
   
  
    public longin() {
        initComponents();
        con.conexao();

        
         
        Thread relogioThread = new Thread(new longin.HoraThread());
        relogioThread.start();
    }
      class HoraThread implements Runnable{

        @Override
        public void run() {
           while(true){
              jLHora.setText(formatoHora.format(new Date()));
               try{
                   Thread.sleep(1000);
               }catch (InterruptedException ex){
                   System.out.println("Thread nao foi finalizada"+ ex);
               }
           }
        }
     }
                               


      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        jLHora = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        sen = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        acessar = new javax.swing.JButton();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pessoa");
        setBackground(new java.awt.Color(0, 0, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nom.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 0, 0));
        nom.setText("nome:");
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 70, 30));

        jLHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLHora.setForeground(new java.awt.Color(102, 102, 102));
        jLHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLHora.setText("hora");
        jLHora.setAutoscrolls(true);
        jLHora.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(jLHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 150, 40));

        senha.setToolTipText("senha");
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 210, 30));

        sen.setBackground(new java.awt.Color(255, 255, 255));
        sen.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        sen.setForeground(new java.awt.Color(255, 0, 0));
        sen.setText("senha:");
        getContentPane().add(sen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 110, 30));

        sair.setBackground(new java.awt.Color(0, 0, 0));
        sair.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        sair.setForeground(new java.awt.Color(255, 0, 51));
        sair.setText("Sair");
        sair.setToolTipText("sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 100, 30));

        acessar.setBackground(new java.awt.Color(0, 0, 0));
        acessar.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        acessar.setForeground(new java.awt.Color(0, 153, 0));
        acessar.setText("Acessar");
        acessar.setToolTipText("entrar");
        acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarActionPerformed(evt);
            }
        });
        getContentPane().add(acessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 110, 30));

        nome.setToolTipText("nome do usuario");
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 210, 30));

        jLabel3.setFont(new java.awt.Font("Vivaldi", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sistema Para Barbearia");
        jLabel3.setToolTipText("CB");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 650, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/torres2.00.jpg"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleDescription("controle bovino");

        setSize(new java.awt.Dimension(655, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void acessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarActionPerformed
        con.executeSql("select * from login where nome='"+nome.getText()+"'");
           try {
               con.rs.first();
           } catch (SQLException ex) {
               Logger.getLogger(longin.class.getName()).log(Level.SEVERE, null, ex);
           }
           try {
               
               if(con.rs.getString("senha").equals(senha.getText())){
               
                   Principal tela = new Principal();
                   tela.setVisible(true);
                   dispose();
               }else
                  
                   JOptionPane.showMessageDialog(rootPane, "senha ou usuario invalida");
           } catch (SQLException ex) {
               Logger.getLogger(longin.class.getName()).log(Level.SEVERE, null, ex);
           }

    
    }//GEN-LAST:event_acessarActionPerformed
   private void formWindohandlingwOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your  code here:
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy ");
       // jLData.setText(formato.format(dataSistema));
        nome.setEditable(false);

  
    }  
    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(longin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(longin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(longin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(longin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new longin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acessar;
    private javax.swing.JLabel jLHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nom;
    private javax.swing.JTextField nome;
    private javax.swing.JButton sair;
    private javax.swing.JLabel sen;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables
}
