package views;
/*
 * TelaConsulta.java
 *
 * Created on 27 de Novembro de 2002, 16:34
 */

import java.util.*;
import java.lang.*;
import java.text.*;
import negocios.*;
import dialogos.*;
/**
 *
 * @author  leme
 */
public class TelaConsulta extends javax.swing.JDialog {
    Paciente paciente = null;
    Consulta consulta = null;
    ArrayList servicos = new ArrayList();
    Vector vetor;
    
    /** Creates new form TelaConsulta */
    public TelaConsulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    
        vetor = new Vector();
        initComponents();
        
        //jComboBoxTratamento = new javax.swing.JComboBox(dcb);
        carregaPacientes ();
        setLocationRelativeTo(parent);       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jComboBoxPacientes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDia = new javax.swing.JTextField();
        jTextField2Horai = new javax.swing.JTextField();
        jTextField2Horaf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAtividade = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jCheckBoxEmergencial = new javax.swing.JCheckBox();
        jTextFieldPacEmerg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxTratamento = new javax.swing.JComboBox(vetor);
        jLabel2 = new javax.swing.JLabel();
        jButtonAdServico = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxServicos = new javax.swing.JComboBox();

        setTitle("Agendamento de consulta");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("telaConsulta"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        painel.setPreferredSize(new java.awt.Dimension(430, 430));
        painel.setLayout(null);
        painel.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 2, 2);

        jComboBoxPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPacientesActionPerformed(evt);
            }
        });
        painel.add(jComboBoxPacientes);
        jComboBoxPacientes.setBounds(20, 40, 390, 20);

        jLabel1.setText("Paciente");
        painel.add(jLabel1);
        jLabel1.setBounds(20, 10, 90, 14);

        jLabel3.setText("Horário Inicial");
        painel.add(jLabel3);
        jLabel3.setBounds(170, 230, 110, 14);

        jTextFieldDia.setToolTipText("dia");
        painel.add(jTextFieldDia);
        jTextFieldDia.setBounds(20, 260, 130, 20);
        painel.add(jTextField2Horai);
        jTextField2Horai.setBounds(200, 260, 70, 20);
        painel.add(jTextField2Horaf);
        jTextField2Horaf.setBounds(340, 260, 70, 20);

        jLabel4.setText("Horário Final");
        painel.add(jLabel4);
        jLabel4.setBounds(310, 230, 100, 14);

        jLabel5.setText("Descrição da Atividade");
        painel.add(jLabel5);
        jLabel5.setBounds(20, 300, 180, 14);
        painel.add(jTextFieldAtividade);
        jTextFieldAtividade.setBounds(20, 330, 390, 20);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        painel.add(jButtonOK);
        jButtonOK.setBounds(100, 370, 90, 23);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        painel.add(jButtonCancelar);
        jButtonCancelar.setBounds(220, 370, 75, 23);

        jCheckBoxEmergencial.setText("Emergencial:");
        jCheckBoxEmergencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEmergencialActionPerformed(evt);
            }
        });
        painel.add(jCheckBoxEmergencial);
        jCheckBoxEmergencial.setBounds(20, 90, 110, 23);

        jTextFieldPacEmerg.setEnabled(false);
        jTextFieldPacEmerg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPacEmergActionPerformed(evt);
            }
        });
        painel.add(jTextFieldPacEmerg);
        jTextFieldPacEmerg.setBounds(140, 90, 270, 20);

        jLabel7.setText("Tratamento");
        painel.add(jLabel7);
        jLabel7.setBounds(20, 140, 100, 14);

        jComboBoxTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTratamentoActionPerformed(evt);
            }
        });
        painel.add(jComboBoxTratamento);
        jComboBoxTratamento.setBounds(130, 140, 280, 20);

        jLabel2.setText("Data");
        painel.add(jLabel2);
        jLabel2.setBounds(20, 230, 52, 14);

        jButtonAdServico.setText("Adiciona Serviço");
        jButtonAdServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdServicoActionPerformed(evt);
            }
        });
        painel.add(jButtonAdServico);
        jButtonAdServico.setBounds(250, 190, 160, 23);

        jLabel6.setText("Serviços");
        painel.add(jLabel6);
        jLabel6.setBounds(20, 190, 60, 14);

        jComboBoxServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicosActionPerformed(evt);
            }
        });
        painel.add(jComboBoxServicos);
        jComboBoxServicos.setBounds(100, 190, 28, 20);

        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicosActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jComboBoxServicosActionPerformed

    private void jButtonAdServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdServicoActionPerformed
        // Add your handling code here:
        DialogoServico ds = new DialogoServico(new javax.swing.JFrame(), true);
        ds.show();
        Servico serv = ds.getServico();
        servicos.add(serv);
        jComboBoxServicos.addItem(serv);
    }//GEN-LAST:event_jButtonAdServicoActionPerformed

    private void jComboBoxTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTratamentoActionPerformed
        // Add your handling code here:
        Object obj = jComboBoxTratamento.getSelectedItem();
        if (obj == null || obj.toString().equals("Nova consulta")) {
            consulta = null;
        } else {
            consulta = (Consulta) obj;
        }
    }//GEN-LAST:event_jComboBoxTratamentoActionPerformed
    
    private void jComboBoxPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPacientesActionPerformed
        paciente = (Paciente) jComboBoxPacientes.getSelectedItem();
        ArrayList lista = paciente.getConsultas();
        jComboBoxTratamento.removeAllItems();
        
        vetor.add(new String("Nova consulta"));

        for (int i = 0; i < lista.size(); i++) {
            // jComboBoxTratamento.addItem(lista.get(i));
            vetor.add (lista.get(i));
        }
    }//GEN-LAST:event_jComboBoxPacientesActionPerformed

    private void carregaPacientes () {
        Consultorio cons = Consultorio.Instance();
        ArrayList lista = cons.getPacientes();       
        for (int i = 0; i < lista.size(); i++) {
            jComboBoxPacientes.addItem(lista.get(i));
        }
    }
    
    private void jCheckBoxEmergencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEmergencialActionPerformed
        // Add your handling code here:
        if (jTextFieldPacEmerg.isEnabled()) {
            jTextFieldPacEmerg.disable();
            jTextFieldPacEmerg.setText("");
            jComboBoxPacientes.enable();
            jComboBoxTratamento.enable();
        } else {
            jTextFieldPacEmerg.enable();
            jTextFieldPacEmerg.setText("digite aqui");
            jComboBoxPacientes.disable();
            jComboBoxTratamento.disable();
            consulta = null;
        }
    }//GEN-LAST:event_jCheckBoxEmergencialActionPerformed

    private void jTextFieldPacEmergActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPacEmergActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextFieldPacEmergActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // Add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        sdf.setLenient(false);
        boolean dadosValidos = true;
        boolean consultaMarcada = false;
        Consulta novaConsulta = null;
        
        String di = jTextFieldDia.getText() + " " + jTextField2Horai.getText();
        String df = jTextFieldDia.getText() + " " + jTextField2Horaf.getText();
        
        Date dataInic = sdf.parse(di,new ParsePosition(0));
        if (dataInic == null)
        {
            new DialogoConfirmacao(new javax.swing.JFrame(), true, "Erro: data inv\u00e1lida",
                                   "Formato de data inv\u00e1lido.").show();
            dadosValidos = false;
        }

        Date dataFim = sdf.parse(df,new ParsePosition(0));
        if (dataFim == null)
        {
            new DialogoConfirmacao(new javax.swing.JFrame(), true, "Erro: data inv\u00e1lida",
                                   "Formato de data inv\u00e1lido.").show();
            dadosValidos = false;
        }

        if (dadosValidos && dataFim.before(dataInic)) {
            new DialogoConfirmacao(new javax.swing.JFrame(), true, "", "Hor�rios inv�lidos.").show();
            dadosValidos = false;
        }

        
        if (dadosValidos) {
            if (jTextFieldPacEmerg.isEnabled()) {
                paciente = new PacienteEmergencial(jTextFieldPacEmerg.getText());
                consulta = null;
            } 
            else if (paciente == null) {
                // Di�logo para selecionar paciente
                new DialogoConfirmacao(new javax.swing.JFrame(), true, "", "Selecione Paciente").show();
                return;
            }

            
            if (consulta == null) {
                if (servicos == null) {
                    novaConsulta = paciente.marcaConsulta(new DateRange(dataInic, dataFim), 
                                               jTextFieldAtividade.getText());
                    if (novaConsulta != null) {
                        new DialogoConfirmacao(new javax.swing.JFrame(), true, "", "Consulta marcada").show();
                        consultaMarcada = true;
                        setVisible(false);
                        dispose();
                    }                     
                } else {
                        novaConsulta = paciente.marcaConsulta(new DateRange(dataInic, dataFim),
                                               jTextFieldAtividade.getText(),
                                               servicos);
                        if (novaConsulta != null) {
                        new DialogoConfirmacao(new javax.swing.JFrame(), true, "", "Consulta marcada").show();
                        consultaMarcada = true;
                        setVisible(false);
                        dispose();
                    } 
                }
            } else {
                if (servicos == null) {
                    novaConsulta = paciente.marcaConsulta(consulta, 
                                           new DateRange(dataInic, dataFim), 
                                           jTextFieldAtividade.getText());
                    if (novaConsulta != null) {
                        new DialogoConfirmacao(new javax.swing.JFrame(), true, "", "Consulta marcada").show();
                        consultaMarcada = true;
                        setVisible(false);
                        dispose();
                    } 
                } else {
                    novaConsulta = paciente.marcaConsulta(consulta, new DateRange(dataInic, dataFim), 
                                           jTextFieldAtividade.getText(),servicos);
                    if (novaConsulta != null) {
                        new DialogoConfirmacao(new javax.swing.JFrame(), true, "", "Consulta marcada").show();
                        consultaMarcada = true;
                        setVisible(false);
                        dispose();
                    }                     
                }
            }
        }
    
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TelaConsulta(new javax.swing.JFrame(), true).show();        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdServico;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckBoxEmergencial;
    private javax.swing.JComboBox jComboBoxPacientes;
    private javax.swing.JComboBox jComboBoxServicos;
    private javax.swing.JComboBox jComboBoxTratamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2Horaf;
    private javax.swing.JTextField jTextField2Horai;
    private javax.swing.JTextField jTextFieldAtividade;
    private javax.swing.JTextField jTextFieldDia;
    private javax.swing.JTextField jTextFieldPacEmerg;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
    
}
