package views;
/*
 * TelaAgendamento.java
 *
 * Created on 27 de Novembro de 2002, 16:34
 */

import java.util.*;
import java.lang.*;
import java.text.*;
import negocios.*;
import dialogos.*;
/**
 *
 * @author  leme
 */
public class TelaTrabalhos extends javax.swing.JDialog {
    Paciente paciente = null;
    Consulta consulta = null;
    ArrayList servicos = new ArrayList();
    Vector vetor;
    
    /** Creates new form TelaAgendamento */
    public TelaTrabalhos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    
        vetor = new Vector();
        initComponents();
        
        //jComboBoxTratamento = new javax.swing.JComboBox(dcb);
        carregaPacientes ();
        setLocationRelativeTo(parent);       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jComboBoxPacientes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDia = new javax.swing.JTextField();
        jTextField2Horai = new javax.swing.JTextField();
        jTextField2Horaf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAtividade = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxTratamento = new javax.swing.JComboBox(vetor);
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamento de consulta");
        setName("telaConsulta"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        painel.setPreferredSize(new java.awt.Dimension(430, 430));
        painel.setLayout(null);
        painel.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 2, 2);

        jComboBoxPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPacientesActionPerformed(evt);
            }
        });
        painel.add(jComboBoxPacientes);
        jComboBoxPacientes.setBounds(20, 40, 390, 20);

        jLabel1.setText("Cliente");
        painel.add(jLabel1);
        jLabel1.setBounds(20, 10, 90, 14);

        jLabel3.setText("Horário Inicial");
        painel.add(jLabel3);
        jLabel3.setBounds(20, 260, 110, 14);

        jTextFieldDia.setToolTipText("dia");
        jTextFieldDia.setEditable(false);
        painel.add(jTextFieldDia);
        jTextFieldDia.setBounds(80, 210, 130, 20);

        jTextField2Horai.setEditable(false);
        painel.add(jTextField2Horai);
        jTextField2Horai.setBounds(140, 260, 70, 20);

        jTextField2Horaf.setEditable(false);
        painel.add(jTextField2Horaf);
        jTextField2Horaf.setBounds(340, 260, 70, 20);

        jLabel4.setText("Horário Final");
        painel.add(jLabel4);
        jLabel4.setBounds(230, 260, 100, 14);

        jLabel5.setText("Descrição da Atividade");
        painel.add(jLabel5);
        jLabel5.setBounds(20, 300, 180, 14);

        jTextFieldAtividade.setEditable(false);
        painel.add(jTextFieldAtividade);
        jTextFieldAtividade.setBounds(20, 330, 390, 20);

        jButtonOK.setText("Fechar");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        painel.add(jButtonOK);
        jButtonOK.setBounds(170, 370, 90, 23);

        jLabel7.setText("Tratamento");
        painel.add(jLabel7);
        jLabel7.setBounds(20, 100, 100, 14);

        jComboBoxTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTratamentoActionPerformed(evt);
            }
        });
        painel.add(jComboBoxTratamento);
        jComboBoxTratamento.setBounds(20, 140, 390, 20);

        jLabel2.setText("Data");
        painel.add(jLabel2);
        jLabel2.setBounds(20, 210, 52, 14);

        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTratamentoActionPerformed
        // Add your handling code here:
        Object obj = jComboBoxTratamento.getSelectedItem();
        if (obj == null) {
            return;
        } else {
            consulta = (Consulta) obj;
        }
        DateRange dr = consulta.getData();
        Date datai = dr.getInicio();
        Date dataf = dr.getFim();
        
        StringBuffer si = new SimpleDateFormat ("dd/MM/yyyy").format(datai, new StringBuffer(),
                                                                new FieldPosition (0)); 
        
        StringBuffer hi = new SimpleDateFormat ("HH:mm").format(datai, new StringBuffer(),
                                                                new FieldPosition (0)); 
        StringBuffer hf = new SimpleDateFormat ("HH:mm").format(dataf, new StringBuffer(),
                                                                new FieldPosition (0)); 
        
               
        jTextField2Horai.setText(hi.toString()); 
        jTextField2Horaf.setText(hf.toString());
        jTextFieldAtividade.setText(consulta.getDescricao());        
        jTextFieldDia.setText(si.toString()); 
        
        
    }//GEN-LAST:event_jComboBoxTratamentoActionPerformed
    
    private void jComboBoxPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPacientesActionPerformed
        paciente = (Paciente) jComboBoxPacientes.getSelectedItem();
        ArrayList lista = paciente.getConsultas();
        jComboBoxTratamento.removeAllItems();
        
        for (int i = 0; i < lista.size(); i++) {            
            Consulta c = (Consulta) lista.get(i);
            vetor.add (c);
            ArrayList lista1 = c.getConsultas();
            for (int j = 0; j < lista1.size(); j++) {            
                Consulta c1 = (Consulta) lista1.get(j);
                vetor.add (c1);
            }
        }
        jTextField2Horai.setText(""); 
        jTextField2Horaf.setText("");
        jTextFieldAtividade.setText("");        
        jTextFieldDia.setText(""); 
    }//GEN-LAST:event_jComboBoxPacientesActionPerformed

    private void carregaPacientes () {
        Consultorio cons = Consultorio.Instance();
        ArrayList lista = cons.getPacientes();       
        for (int i = 0; i < lista.size(); i++) {
            jComboBoxPacientes.addItem(lista.get(i));
        }
    }
    
    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TelaAgendamento(new javax.swing.JFrame(), true).show();        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxPacientes;
    private javax.swing.JComboBox jComboBoxTratamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2Horaf;
    private javax.swing.JTextField jTextField2Horai;
    private javax.swing.JTextField jTextFieldAtividade;
    private javax.swing.JTextField jTextFieldDia;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
    
}
