package views;
/*
 * TelaExame.java
 *
 * Created on 27 de Novembro de 2002, 16:31
 */

/**
 *
 * @author  leme
 */
public class TelaExame extends javax.swing.JDialog {
    
    /** Creates new form TelaExame */
    public TelaExame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        jComboBoxPacientes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxExames = new javax.swing.JComboBox();
        jTextFieldDiap = new javax.swing.JTextField();
        jTextFieldAnop = new javax.swing.JTextField();
        jTextFieldMesp = new javax.swing.JTextField();
        jTextFieldDiae = new javax.swing.JTextField();
        jTextFieldAnoe = new javax.swing.JTextField();
        jTextFieldMese = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldExame = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setTitle("Pedido de exame");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("telaExame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        painel.setPreferredSize(new java.awt.Dimension(430, 360));
        painel.setLayout(null);
        painel.add(jComboBoxPacientes);
        jComboBoxPacientes.setBounds(20, 50, 390, 20);

        jLabel1.setText("Paciente");
        painel.add(jLabel1);
        jLabel1.setBounds(20, 20, 90, 14);

        jLabel2.setText("Exames");
        painel.add(jLabel2);
        jLabel2.setBounds(20, 100, 60, 30);
        painel.add(jComboBoxExames);
        jComboBoxExames.setBounds(90, 100, 320, 20);

        jTextFieldDiap.setToolTipText("dia");
        painel.add(jTextFieldDiap);
        jTextFieldDiap.setBounds(150, 190, 30, 20);
        painel.add(jTextFieldAnop);
        jTextFieldAnop.setBounds(230, 190, 50, 20);
        painel.add(jTextFieldMesp);
        jTextFieldMesp.setBounds(190, 190, 30, 20);

        jTextFieldDiae.setToolTipText("dia");
        painel.add(jTextFieldDiae);
        jTextFieldDiae.setBounds(150, 230, 30, 20);
        painel.add(jTextFieldAnoe);
        jTextFieldAnoe.setBounds(230, 230, 50, 20);
        painel.add(jTextFieldMese);
        jTextFieldMese.setBounds(190, 230, 30, 20);

        jLabel3.setText("Data da Entrega");
        painel.add(jLabel3);
        jLabel3.setBounds(20, 230, 120, 14);

        jLabel4.setText("Data do Pedido");
        painel.add(jLabel4);
        jLabel4.setBounds(20, 190, 73, 14);

        jLabel5.setText("Exame");
        painel.add(jLabel5);
        jLabel5.setBounds(20, 150, 50, 14);
        painel.add(jTextFieldExame);
        jTextFieldExame.setBounds(90, 150, 320, 20);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        painel.add(jButtonOK);
        jButtonOK.setBounds(110, 290, 95, 23);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        painel.add(jButtonCancelar);
        jButtonCancelar.setBounds(220, 290, 75, 23);

        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TelaExame(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxExames;
    private javax.swing.JComboBox jComboBoxPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldAnoe;
    private javax.swing.JTextField jTextFieldAnop;
    private javax.swing.JTextField jTextFieldDiae;
    private javax.swing.JTextField jTextFieldDiap;
    private javax.swing.JTextField jTextFieldExame;
    private javax.swing.JTextField jTextFieldMese;
    private javax.swing.JTextField jTextFieldMesp;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
    
}
