/*
 * TelaDespesa.java
 *
 * Created on 27 de Novembro de 2002, 16:15
 */

package views;

import negocios.*;
import dialogos.*;
import java.util.*;
import java.text.*;

/**
 *
 * @author  leme
 */
public class TelaDespesa extends javax.swing.JDialog {
    
    /** Creates new form TelaDespesa */
    public TelaDespesa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rdbNenhum.setVisible(false);
        setLocationRelativeTo(parent);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgTipoDespesa = new javax.swing.ButtonGroup();
        painel = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnLimpa = new javax.swing.JButton();
        pnlTipoDespesa = new javax.swing.JPanel();
        rdbMensal = new javax.swing.JRadioButton();
        rdbIndividual = new javax.swing.JRadioButton();
        rdbNenhum = new javax.swing.JRadioButton();
        lblPrestacoes = new javax.swing.JLabel();
        txtPrestacoes = new javax.swing.JTextField();

        setTitle("Registro de despesa");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("telaDespesa"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        painel.setPreferredSize(new java.awt.Dimension(392, 265));
        painel.setMinimumSize(new java.awt.Dimension(0, 0));
        painel.setLayout(null);

        lblData.setText("Data:");
        lblData.setForeground(new java.awt.Color(0, 0, 153));
        lblData.setName("lblData"); // NOI18N
        painel.add(lblData);
        lblData.setBounds(20, 70, 40, 14);

        lblDescricao.setText("Descrição:");
        lblDescricao.setForeground(new java.awt.Color(0, 0, 153));
        lblDescricao.setName("lblDescricao"); // NOI18N
        painel.add(lblDescricao);
        lblDescricao.setBounds(20, 100, 80, 14);

        lblValor.setText("Valor:");
        lblValor.setForeground(new java.awt.Color(0, 0, 153));
        lblValor.setName("lblValor"); // NOI18N
        painel.add(lblValor);
        lblValor.setBounds(20, 130, 50, 14);

        txtData.setName("txtData"); // NOI18N
        painel.add(txtData);
        txtData.setBounds(60, 70, 90, 20);

        txtDescricao.setName("txtDescricao"); // NOI18N
        painel.add(txtDescricao);
        txtDescricao.setBounds(100, 100, 280, 20);

        txtValor.setName("txtValor"); // NOI18N
        painel.add(txtValor);
        txtValor.setBounds(70, 130, 60, 20);

        btnOk.setMnemonic('O');
        btnOk.setText("Ok");
        btnOk.setName("btnOk"); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        painel.add(btnOk);
        btnOk.setBounds(100, 210, 90, 23);

        btnLimpa.setMnemonic('L');
        btnLimpa.setText("Limpa");
        btnLimpa.setName("btnLimpa"); // NOI18N
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });
        painel.add(btnLimpa);
        btnLimpa.setBounds(210, 210, 90, 23);

        pnlTipoDespesa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo da despesa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N
        pnlTipoDespesa.setLayout(null);

        rdgTipoDespesa.add(rdbMensal);
        rdbMensal.setText("Mensal");
        rdbMensal.setName("rdbMensal"); // NOI18N
        rdbMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMensalActionPerformed(evt);
            }
        });
        pnlTipoDespesa.add(rdbMensal);
        rdbMensal.setBounds(10, 20, 70, 23);

        rdgTipoDespesa.add(rdbIndividual);
        rdbIndividual.setText("Individual");
        rdbIndividual.setName("rdbIndividual"); // NOI18N
        rdbIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbIndividualActionPerformed(evt);
            }
        });
        pnlTipoDespesa.add(rdbIndividual);
        rdbIndividual.setBounds(90, 20, 100, 23);

        rdgTipoDespesa.add(rdbNenhum);
        rdbNenhum.setName("rdbNenhum"); // NOI18N
        rdbNenhum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNenhumActionPerformed(evt);
            }
        });
        pnlTipoDespesa.add(rdbNenhum);
        rdbNenhum.setBounds(180, 0, 20, 31);

        painel.add(pnlTipoDespesa);
        pnlTipoDespesa.setBounds(10, 0, 200, 60);

        lblPrestacoes.setText("Número de prestações:");
        lblPrestacoes.setForeground(new java.awt.Color(0, 0, 153));
        lblPrestacoes.setName("lblPrestacoes"); // NOI18N
        painel.add(lblPrestacoes);
        lblPrestacoes.setBounds(20, 160, 170, 14);

        txtPrestacoes.setName("txtPrestacoes"); // NOI18N
        txtPrestacoes.setEnabled(false);
        painel.add(txtPrestacoes);
        txtPrestacoes.setBounds(190, 160, 30, 20);

        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbNenhumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNenhumActionPerformed
        txtPrestacoes.setText(null);
        txtPrestacoes.disable();
    }//GEN-LAST:event_rdbNenhumActionPerformed

    private void rdbIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbIndividualActionPerformed
        txtPrestacoes.setText(null);
        txtPrestacoes.disable();
    }//GEN-LAST:event_rdbIndividualActionPerformed

    private void rdbMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMensalActionPerformed
        txtPrestacoes.enable();
    }//GEN-LAST:event_rdbMensalActionPerformed

    private void limpaCampos()
    {
        rdbNenhum.setSelected(true);
        txtData.setText(null);
        txtDescricao.setText(null);
        txtValor.setText(null);
        txtPrestacoes.setText(null);
    }

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        Date data = null;
        String descricao = new String();
        Quantity valor = new Quantity(0,Unit.get(Unit.REAL));
        int prestacoes = 0;
        PoliticaDeDespesa politica = null;
        boolean dadosValidos = true;
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);
        data = sdf.parse(txtData.getText(),new ParsePosition(0));
        if (data == null)
        {
            new DialogoConfirmacao(new javax.swing.JFrame(), true, "Erro: data inv\u00e1lida",
                                   "Formato de data inv\u00e1lido.").show();
            dadosValidos = false;
        }

        descricao = txtDescricao.getText();
        
        try {
            valor = new Quantity(Double.parseDouble(txtValor.getText()),Unit.get(Unit.REAL));
        }
        catch (NumberFormatException nfe) {
            new DialogoConfirmacao(new javax.swing.JFrame(), true , "Erro: valor inv\u00e1lido",
                                   "Formato de valor real inv\u00e1lido.").show();
            dadosValidos = false;
        }
        
        if (rdbMensal.isSelected())
        {
            try {
                prestacoes = Integer.parseInt(txtPrestacoes.getText());
                politica = new DespesaMensal(prestacoes);
            }
            catch (NumberFormatException nfe) {
                new DialogoConfirmacao(new javax.swing.JFrame(), true , "Erro: presta��es inv\u00e1lidas",
                                       "Formato de valor inteiro inv\u00e1lido.").show();
                dadosValidos = false;
            }
        }
        else
            if (rdbIndividual.isSelected())
                politica = new DespesaIndividual();
            else {
                new DialogoConfirmacao(new javax.swing.JFrame(), true , "Erro: selecione o tipo de despesa",
                                       "Tipo da despesa em branco.").show();
                dadosValidos = false;
            }
        
        if (dadosValidos) {
            Consultorio consultorio = Consultorio.Instance();
            consultorio.adicionaDespesa(new Despesa(data,descricao,valor,politica));
            new DialogoConfirmacao(new javax.swing.JFrame(), true, "Aviso",
                                   "Despesa inclu\u00edda com sucesso.").show();
            limpaCampos();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
        limpaCampos();
        txtPrestacoes.disable();
    }//GEN-LAST:event_btnLimpaActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TelaDespesa(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpa;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblPrestacoes;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel painel;
    private javax.swing.JPanel pnlTipoDespesa;
    private javax.swing.JRadioButton rdbIndividual;
    private javax.swing.JRadioButton rdbMensal;
    private javax.swing.JRadioButton rdbNenhum;
    private javax.swing.ButtonGroup rdgTipoDespesa;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPrestacoes;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
    
}
